Repository COS301-SE-2022/ReverseHand, pull requests merged in 2022-08, with the labels that each got.

#323 Amplify
  apps/app/integration_test/consumer_view_ads_test.dart
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner.xcodeproj/project.pbxproj
  apps/app/lib/main.dart
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/amplify/.gitignore
  libs/amplify/amplify/backend/auth/reversehandc4d19aa6c4d19aa6/cli-inputs.json
  libs/amplify/amplify/backend/auth/userPoolGroups/user-pool-group-precedence.json
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/storage/S3ReverseHand/cli-inputs.json
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/amplify/pubspec.yaml
  libs/authentication/pubspec.yaml
  libs/authentication/test/authentication_test.dart
  libs/geolocation/lib/pages/location_confirm_page.dart
  libs/geolocation/lib/place_api_service.dart
  libs/geolocation/pubspec.yaml
  libs/redux_comp/lib/actions/add_to_bucket_action.dart
  libs/redux_comp/lib/actions/adverts/close_advert_action.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/accept_bid_action.dart
  libs/redux_comp/lib/actions/bids/delete_bid_action.dart
  libs/redux_comp/lib/actions/bids/edit_bid_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/chat/create_chat_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/actions/chat/send_message_action.dart
  libs/redux_comp/lib/actions/chat/subscribe_messages_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/user/add_user_to_group_action.dart
  libs/redux_comp/lib/actions/user/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/create_user_action.dart
  libs/redux_comp/lib/actions/user/edit_user_details_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/actions/user/logout_action.dart
  libs/redux_comp/lib/actions/user/register_user_action.dart
  libs/redux_comp/lib/actions/user/verify_user_action.dart
  libs/redux_comp/pubspec.yaml
Labels: Status : Ready, Priority:Medium, Scope : Back End

#329 (✨Auth) : AutoLogin
  apps/app/ios/Podfile.lock
  libs/amplify/amplify/backend/auth/reversehandc4d19aa6c4d19aa6/cli-inputs.json
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/usertype_selection_page.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/intiate_auth_action.dart
  libs/redux_comp/lib/actions/refresh_user_token_action.dart
  libs/redux_comp/lib/actions/user/add_user_to_group_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/actions/user/register_user_action.dart
  libs/redux_comp/lib/actions/user/verify_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/user_models/cognito_auth_model.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/widgets/multiselect_widget.dart
Labels: Status : Ready

#330 Tradesman
  libs/general/lib/widgets/profile_divider.dart
  libs/redux_comp/lib/actions/adverts/filter_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/intiate_auth_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/filter_adverts_model.dart
  libs/redux_comp/lib/models/geolocation/coordinates_model.dart
  libs/redux_comp/lib/models/geolocation/domain_model.dart
  libs/tradesman/lib/pages/activity_stream_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/notification_card_widget.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
Labels: Priority:Medium, Scope : Front End

#331 (♺Auth): Changed Advert to store a Domain model instead of a String city
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/auth/reversehandc4d19aa6c4d19aa6/cli-inputs.json
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/addReviewResolver/src/index.js
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/getNotificationsResolver/amplify.state
  libs/amplify/amplify/backend/function/getNotificationsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/getNotificationsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/parameters.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/src/event.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/src/index.js
  libs/amplify/amplify/backend/function/getNotificationsResolver/src/package.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/viewAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/lib/pages/usertype_selection_page.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/geolocation/lib/pages/custom_location_search_page.dart
  libs/geolocation/lib/place_api_service.dart
  libs/geolocation/pubspec.yaml
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/login_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/logout_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/register_user_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/verify_user_action.dart
  libs/redux_comp/lib/actions/user/cognito/add_user_to_group_action.dart
  libs/redux_comp/lib/actions/user/cognito/intiate_auth_action.dart
  libs/redux_comp/lib/actions/user/cognito/refresh_user_token_action.dart
  libs/redux_comp/lib/actions/user/user_table/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/user_table/create_user_action.dart
  libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/lib/actions/user/user_table/remove_domain_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/tradesman/lib/pages/activity_stream_page.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/card_widget.dart
  libs/tradesman/lib/widgets/notification_card_widget.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Priority:Medium, Type: Change, Scope : Back End

#344 Tradesman
  apps/app/android/app/build.gradle
  apps/app/integration_test/consumer_create_advert.dart
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/auth/reversehandc4d19aa6c4d19aa6/cli-inputs.json
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/amplify.state
  libs/amplify/amplify/backend/function/deleteReviewResolver/custom-policies.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/deleteReviewResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/function-parameters.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/parameters.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/src/event.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/src/index.js
  libs/amplify/amplify/backend/function/deleteReviewResolver/src/package.json
  libs/amplify/amplify/backend/function/deleteReviewResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/amplify.state
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/getUserStatisticsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/parameters.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/event.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/index.js
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/package.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/authentication/lib/pages/login_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/widgets/consumer_floating_button.dart
  libs/consumer/lib/widgets/filter_popup.dart
  libs/general/lib/widgets/pop_up.dart
  libs/redux_comp/lib/actions/adverts/filter_adverts_action.dart
  libs/redux_comp/lib/actions/geolocation/get_geolocation_permission_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/filter_adverts_model.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
  libs/tradesman/lib/widgets/tradesman_floating_button.dart
Labels: Type: Fix, Type: Change, Scope : Front End, Scope : Back End

#345 💫Delete and Add review reducers
  libs/redux_comp/lib/actions/user/add_review_action.dart
  libs/redux_comp/lib/actions/user/delete_review_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/review_model.dart
Labels: Priority:Medium, Scope : Back End

#349 Tradesman
  apps/app/ios/Podfile.lock
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/general/lib/methods/time.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/models/advert_model.dart
Labels: Status : Ready, Priority:Medium, Scope : Back End

#354 Amplify
  apps/app/ios/Podfile.lock
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createUserResolver/src/index.js
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/index.js
  libs/redux_comp/lib/actions/add_to_bucket_action.dart
  libs/redux_comp/lib/actions/get_from_bucket_action.dart
  libs/redux_comp/lib/actions/get_profile_photo_action.dart
  libs/redux_comp/lib/actions/user/add_review_action.dart
  libs/redux_comp/lib/actions/user/cognito/get_cognito_user_action.dart
  libs/redux_comp/lib/actions/user/delete_review_action.dart
  libs/redux_comp/lib/models/bucket_model.dart
  libs/redux_comp/lib/models/review_model.dart
Labels: Priority:Medium, Scope : Back End

#373 🧮User Statistics
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/acceptBidResolver/acceptBidResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/acceptBidResolver/src/index.js
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/index.js
  libs/amplify/amplify/backend/function/shortListBidResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
Labels: Priority:Medium, Scope : Back End

#374 Consumer
  libs/authentication/lib/pages/signup_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/job_creation_popup.dart
  libs/consumer/lib/widgets/light_dialog_helper.dart
  libs/consumer/lib/widgets/light_pop_up.dart
  libs/general/lib/widgets/dark_dialog_helper.dart
  libs/general/lib/widgets/hint_widget.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/pop_up.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/general/lib/widgets/textfield.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/widgets/tradesman_floating_button.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Priority:Medium, Scope : Front End

#375 💫Created reducer for GetUserStatisticsResolver
  libs/redux_comp/lib/actions/user/get_user_statistics_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/user_models/consumer_stats_model.dart
  libs/redux_comp/lib/models/user_models/statistics_model.dart
  libs/redux_comp/lib/models/user_models/tradesman_stats_model.dart
Labels: Priority:Medium, Scope : Back End

#378 Chat
  documentation/SRS_Capstone_V3.pdf
  libs/chat/lib/pages/chat_page.dart
Labels: Priority:Medium, Scope : Front End

#387 Consumer
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/rating_popup.dart
  libs/general/lib/widgets/bottom_sheet.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/pop_up.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
Labels: Priority:Medium, Scope : Front End

#388 Payments
  apps/app/ios/Podfile.lock
  libs/admin/project.json
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/addAdvertReportResolver/src/index.js
  libs/amplify/amplify/backend/function/createUserResolver/src/index.js
  libs/amplify/amplify/backend/function/getCustomerReportedAdverts/src/index.js
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/amplify.state
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/getPayStackApiKeysResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/parameters.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/src/event.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/src/index.js
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/src/package.json
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/src/secretesmanager.js
  libs/amplify/amplify/backend/function/getPayStackApiKeysResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/amplify.state
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/getReportedAdvertsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/parameters.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/src/event.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/src/package.json
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getReportedCustomers/src/index.js
  libs/amplify/amplify/backend/function/removeAdvertReportResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/chat/project.json
  libs/consumer/lib/pages/advert_details_page.dart
  libs/geolocation/project.json
  libs/notifications/project.json
  libs/redux_comp/lib/actions/get_paystack_secrets_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/process_payment_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/pubspec.yaml
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#390 💫Redux: Ranking adverts
  apps/app/pubspec.lock
  libs/redux_comp/lib/actions/adverts/rank_adverts_action.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/pubspec.yaml
Labels: Priority:Medium, Scope : Back End

#393 (Refactor): Merge branch
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner.xcodeproj/project.pbxproj
  apps/app/pubspec.lock
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/lib/widgets/auth_button.dart
  libs/authentication/lib/widgets/forgot_pass_popup.dart
  libs/authentication/lib/widgets/link_widget.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/widgets/chat_appbar_widget.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/widgets/radio_select_widget.dart
  libs/general/lib/widgets/blue_button_widget.dart
  libs/general/lib/widgets/button.dart
  libs/general/lib/widgets/profile_image.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/redux_comp/lib/models/geolocation/coordinates_model.dart
  libs/redux_comp/lib/models/geolocation/domain_model.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/multiselect_widget.dart
  libs/tradesman/lib/widgets/place_bid_popup_widget.dart
Labels: Status : Ready, Scope : Front End
