Repository COS301-SE-2022/ReverseHand, pull requests merged in 2022-09, with the labels that each got.

#397 Consumer
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner.xcodeproj/project.pbxproj
  apps/app/lib/main.dart
  libs/admin/lib/pages/admin_consumer_reports_page.dart
  libs/admin/lib/pages/admin_content_page.dart
  libs/admin/lib/widgets/quickview_reported_advert_widget.dart
  libs/consumer/lib/pages/activity_stream_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/consumer/lib/widgets/shortlist_bid_popup.dart
  libs/general/lib/pages/activity_stream.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/lib/pages/activity_stream_page.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#400 Tradesman
  apps/app/lib/main.dart
  libs/admin/lib/pages/admin_advert_details_page.dart
  libs/admin/lib/pages/admin_content_page.dart
  libs/admin/lib/widgets/quickview_reported_advert_widget.dart
  libs/chat/lib/pages/chat_selection_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/widgets/new_radio_select.dart
  libs/geolocation/test/geolocation_test.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
Labels: Priority:Medium, Scope : Front End

#401 Auth
  apps/app/ios/Podfile.lock
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/analytics/reversehandPinpoint/parameters.json
  libs/amplify/amplify/backend/analytics/reversehandPinpoint/pinpoint-cloudformation-template.json
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/addAdvertReportResolver/src/index.js
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/removeReviewReportResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/notifications/test/notifications_test.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/user/user_table/create_user_action.dart
  libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/pubspec.yaml
Labels: Priority:High

#403 🐛 Removed amplifyconfig from gitignore
  apps/app/pubspec.lock
  libs/amplify/.gitignore
Labels: Priority:High

#406 (♻️ Auth) : signup works again
  apps/app/lib/main.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/redux_comp/lib/actions/geolocation/set_place_action.dart
  libs/redux_comp/lib/actions/user/user_table/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/multiselect_widget.dart
Labels: Priority:Medium, Scope : Back End

#408 Tradesman
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/consumer_floating_button.dart
  libs/general/lib/methods/job_icons.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/quick_view_bid_widget.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
Labels: Priority:Medium, Scope : Front End

#409 :ambulance: Amplify
  libs/admin/lib/pages/admin_advert_details_page.dart
  libs/chat/lib/pages/chat_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/bottom_sheet.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/multiselect_widget.dart
Labels: Priority:Medium

#410 Amplify
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/addAdvertReportResolver/src/index.js
  libs/amplify/amplify/backend/function/archiveAdvertResolver/archiveAdvertResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/archiveAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/getReportedAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/function/getReportedReviewsResolver/src/index.js
  libs/amplify/amplify/backend/function/getReportedUsersResolver/src/index.js
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/getUserStatisticsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getUserStatisticsResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/redux_comp/lib/actions/user/get_user_statistics_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_models/statistics_model.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Status : Ready, Priority:Medium, Scope : Front End, Scope : Back End

#411 (Refactor): UI Updates
  libs/admin/lib/pages/admin_content_page.dart
  libs/admin/lib/pages/admin_metrics_page.dart
  libs/admin/lib/pages/admin_users_page.dart
  libs/authentication/lib/methods/validation.dart
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/lib/widgets/auth_textfield_light.dart
  libs/authentication/lib/widgets/forgot_password_popups/email_popup_widget.dart
  libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
  libs/authentication/lib/widgets/forgot_password_popups/otp_popup_widget.dart
  libs/authentication/lib/widgets/link_widget.dart
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/pages/chat_selection_page.dart
  libs/chat/lib/widgets/action_bar_widget.dart
  libs/chat/lib/widgets/action_button_widget.dart
  libs/chat/lib/widgets/chat_appbar_widget.dart
  libs/chat/lib/widgets/quick_view_chat_widget.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/general/lib/pages/activity_stream.dart
  libs/general/lib/widgets/hint_widget.dart
  libs/general/lib/widgets/loading_widget.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
Labels: Status : Ready, Scope : Front End

#412 (Amplify) : Broke a bunch, but it works now hehe
  apps/app/ios/Podfile.lock
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/acceptBidResolver/src/index.js
  libs/amplify/amplify/backend/function/addReviewResolver/addReviewResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/addReviewResolver/src/index.js
  libs/amplify/amplify/backend/function/addUserToGroupResolver/src/index.js
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/createUserResolver/createUserResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/createUserResolver/src/index.js
  libs/amplify/amplify/backend/function/editUserDetailResolver/editUserDetailResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/editUserDetailResolver/src/index.js
  libs/amplify/amplify/backend/function/getNotificationsResolver/getNotificationsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getNotificationsResolver/src/index.js
  libs/amplify/amplify/backend/function/notificationsResolver/notificationsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/notificationsResolver/src/index.js
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/backend/function/shortListBidResolver/src/index.js
  libs/amplify/amplify/backend/function/viewAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/function/viewUserResolver/src/index.js
  libs/amplify/amplify/backend/function/viewUserResolver/viewUserResolver-cloudformation-template.json
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/redux_comp/lib/actions/user/user_table/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_models/statistics_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/redux_comp/test/redux_test.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Priority:Medium, Scope : Back End

#414 Tradesman UI
  apps/app/lib/main.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/widgets/shortlist_bid_popup.dart
  libs/general/lib/methods/job_icons.dart
  libs/general/lib/pages/activity_stream.dart
  libs/general/lib/widgets/bottom_sheet.dart
  libs/general/lib/widgets/button.dart
  libs/general/lib/widgets/long_button_transparent.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/tradesman/lib/methods/currency_formatter.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_quote_sheet.dart
  libs/tradesman/pubspec.yaml
Labels: Priority:Medium, Scope : Front End

#415 (Refactor): UI Updates
  apps/app/pubspec.lock
  libs/admin/lib/pages/admin_advert_details_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/assets/images/bedroom_mock.png
  libs/general/assets/images/kitchen_mock.png
  libs/general/assets/images/living_mock.png
  libs/general/lib/pages/image_viewer_page.dart
  libs/general/lib/widgets/appbar.dart
  libs/general/lib/widgets/appbar_popup_menu_widget.dart
  libs/general/lib/widgets/image_carousel_widget.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/pubspec.yaml
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/view_bids_page.dart
Labels: Status : Ready, Scope : Front End

#420 Amplify
  libs/consumer/lib/pages/advert_details_page.dart
  libs/general/lib/widgets/image_carousel_widget.dart
  libs/general/lib/widgets/profile_image.dart
  libs/redux_comp/lib/actions/add_to_bucket_action.dart
  libs/redux_comp/lib/actions/adverts/get_advert_images_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/user/get_profile_photo_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/bucket_model.dart
  libs/tradesman/lib/pages/advert_details.dart
  package-lock.json
  package.json
Labels: Priority:Medium, Scope : Back End

#422 Tradesman
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/widgets/accept_bid_popup.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/bid_details_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/widgets/quick_view_bid_widget.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#425 Amplify
  libs/admin/lib/widgets/admin_navbar_widget.dart
  libs/authentication/lib/pages/usertype_selection_page.dart
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/pages/chat_selection_page.dart
  libs/chat/lib/widgets/quick_view_chat_widget.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/general/lib/methods/job_icons.dart
  libs/general/lib/pages/activity_stream.dart
  libs/general/lib/widgets/profile_image.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/geolocation/lib/pages/location_confirm_page.dart
  libs/redux_comp/lib/actions/add_to_bucket_action.dart
  libs/redux_comp/lib/actions/admin/get_reported_customers_action.dart
  libs/redux_comp/lib/actions/adverts/get_bid_on_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/rank_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/bids/set_active_bid_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/chat/create_chat_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/actions/chat/send_message_action.dart
  libs/redux_comp/lib/actions/geolocation/set_place_action.dart
  libs/redux_comp/lib/actions/user/cognito/assign_groups_action.dart
  libs/redux_comp/lib/actions/user/cognito/get_cognito_user_action.dart
  libs/redux_comp/lib/actions/user/cognito/refresh_user_token_action.dart
  libs/redux_comp/lib/actions/user/get_notifications_action.dart
  libs/redux_comp/lib/actions/user/get_other_user_action.dart
  libs/redux_comp/lib/actions/user/get_profile_photo_action.dart
  libs/redux_comp/lib/actions/user/get_user_statistics_action.dart
  libs/redux_comp/lib/actions/user/subscribe_notifications_action.dart
  libs/redux_comp/lib/actions/user/user_table/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/user_table/create_user_action.dart
  libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/lib/actions/user/user_table/remove_domain_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/geolocation/address_model.dart
  libs/redux_comp/lib/models/geolocation/domain_model.dart
  libs/redux_comp/lib/models/geolocation/location_model.dart
  libs/redux_comp/lib/models/user_models/statistics_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/edit_bid_page.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/place_bid_popup_widget.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
  libs/tradesman/lib/widgets/tradesman_navbar_widget.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#431 Lambda Test run
  .github/workflows/android.yml
  .gitignore
  .vscode/extensions.json
  jest.config.ts
  jest.preset.js
  libs/amplify/jest.config.ts
  libs/amplify/project.json
  libs/amplify/test/test_integration.test.js
  libs/amplify/tsconfig.json
  libs/amplify/tsconfig.spec.json
  migrations.json
  nx.json
  package-lock.json
  package.json
  workspace.json
Labels: Priority:Medium, Scope : Back End, Scope: CI/CD

#438 Tradesman
  libs/admin/lib/pages/admin_manage_page.dart
  libs/admin/lib/pages/app_management/report_manage_page.dart
  libs/admin/lib/pages/app_management/user_manage_page.dart
  libs/admin/lib/widgets/admin_navbar_widget.dart
  libs/admin/lib/widgets/admin_user_widget.dart
  libs/admin/lib/widgets/quickview_report_widget.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/limited_consumer_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/long_button_transparent.dart
  libs/general/lib/widgets/long_button_widget.dart
  libs/geolocation/lib/pages/location_confirm_page.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/card_widget.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_quote_sheet.dart
Labels: Priority:Medium, Scope : Front End

#439 Amplify
  apps/app/ios/Podfile.lock
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/editBidResolver/src/index.js
  libs/amplify/amplify/backend/function/getMetricsResolver/src/index.js
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/backend/function/shortListBidResolver/src/index.js
  libs/amplify/amplify/backend/function/viewBidsResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/chat/lib/pages/chat_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/bids/edit_bid_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/tradesman/lib/methods/populate_bids.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/bid_details_page.dart
  libs/tradesman/lib/widgets/place_bid_popup_widget.dart
  libs/tradesman/lib/widgets/quick_view_bid_widget.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_quote_sheet.dart
Labels: Priority:Medium, Scope : Back End

#442 Tradesman
  apps/app/lib/main.dart
  libs/admin/lib/pages/admin_profile_page.dart
  libs/admin/lib/pages/app_management/advert_reports/review_advert_reports_page.dart
  libs/admin/lib/widgets/admin_navbar_widget.dart
  libs/admin/lib/widgets/admin_user_widget.dart
  libs/admin/lib/widgets/quickview_report_widget.dart
  libs/admin/lib/widgets/quickview_reported_advert_widget.dart
  libs/admin/lib/widgets/report_details_widget.dart
  libs/admin/lib/widgets/report_user_descr_widget.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/limited_consumer_page.dart
  libs/consumer/lib/pages/limited_consumer_profile_page.dart
  libs/consumer/pubspec.yaml
  libs/tradesman/lib/methods/currency_formatter.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/reviews/review_widget.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/edit_bid_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
Labels: Priority:Medium, Scope : Front End

#450 Tradesman
  apps/app/lib/main.dart
  libs/admin/lib/pages/app_management/advert_reports/view_advert_reports_page.dart
  libs/authentication/lib/widgets/forgot_password_popups/email_popup_widget.dart
  libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
  libs/authentication/lib/widgets/forgot_password_popups/otp_popup_widget.dart
  libs/consumer/lib/pages/limited_consumer_profile_page.dart
  libs/general/lib/pages/report_page.dart
  libs/general/lib/widgets/textfield.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_quote_sheet.dart
Labels: Priority:Medium, Scope : Front End

#451 Amplify
  apps/app/android/app/src/main/AndroidManifest.xml
  apps/app/ios/Runner/Info.plist
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/addAdvertReportResolver/src/index.js
  libs/amplify/amplify/backend/function/getBidOnAdvertsResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/advert_details_page.dart
  libs/redux_comp/lib/actions/adverts/filter_adverts_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/user/reviews/add_review_action.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/filter_adverts_model.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
Labels: Priority:Medium

#458 Auth
  libs/amplify/amplify/backend/function/viewJobsResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
Labels: Priority:Medium

#460 💫Some Lambda tests
  apps/app/pubspec.lock
  execute_script.js
  libs/amplify/.gitignore
  libs/amplify/coverage/lcov.info
  libs/amplify/test/closeAdvertResolver.test.js
  libs/amplify/test/creation.test.js
  libs/amplify/test/editing.test.js
  libs/amplify/test/getBidsOnAdvertResolver.test.js
  libs/amplify/test/viewUserResolver.test.js
Labels: Priority:Medium, Type: Test, Scope : Back End

#462 🐛 Fixed APK issue
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
Labels: Priority:High, Scope : Back End

#463 Tradesman UI
  apps/app/pubspec.lock
  libs/admin/lib/pages/app_management/advert_reports/view_advert_reports_page.dart
  libs/admin/lib/pages/app_management/review_reports/review_report_manage_page.dart
  libs/admin/lib/pages/app_management/view_user_reports_page.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/limited_consumer_profile_page.dart
  libs/consumer/lib/widgets/filter_popup.dart
  libs/general/lib/methods/job_icons.dart
  libs/general/lib/widgets/bottom_sheet.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/list_refresh_widget.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/textfield.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/widgets/tradesman_filter_popup.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/edit_bid_sheet.dart
Labels: Priority:Medium, Scope : Front End

#467 Amplify
  apps/app/ios/Podfile
  apps/app/ios/Podfile.lock
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/amplify/amplify/backend/analytics/reversehandPinpoint/parameters.json
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/viewAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/amplify/pubspec.yaml
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/redux_comp/lib/actions/adverts/archive_advert_action.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/get_bid_on_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/analytics_events/record_create_advert_action.dart
  libs/redux_comp/lib/actions/bids/accept_bid_action.dart
  libs/redux_comp/lib/actions/bids/delete_bid_action.dart
  libs/redux_comp/lib/actions/bids/edit_bid_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/chat/create_chat_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/user/user_table/get_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/edit_bid_sheet.dart
Labels: Priority:Medium

#468 Tradesman UI
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/limited_consumer_profile_page.dart
  libs/consumer/lib/widgets/new_radio_select.dart
  libs/consumer/lib/widgets/radio_select_widget.dart
  libs/general/lib/methods/toast_error.dart
  libs/general/lib/pages/report_page.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/pages/reviews_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
Labels: Scope : Front End

#471 Tradesman UI overflow fixes
  libs/chat/lib/widgets/quick_view_chat_widget.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/edit_bid_sheet.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
Labels: Priority:High, Scope : Front End

#474 Amplify
  apps/app/ios/Podfile
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner.xcodeproj/project.pbxproj
  apps/app/ios/Runner/Info.plist
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/analytics/reversehandPinpoint/pinpoint-cloudformation-template.json
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/acceptBidResolver/acceptBidResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/acceptBidResolver/src/index.js
  libs/amplify/amplify/backend/function/editAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/placeBidResolver/placeBidResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/backend/function/shortListBidResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplifyconfiguration.dart
  libs/amplify/pubspec.yaml
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/widgets/chat_appbar_widget.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/widgets/consumer_navbar.dart
  libs/general/lib/pages/archived_advert_details_page.dart
  libs/general/lib/widgets/image_carousel_widget.dart
  libs/general/lib/widgets/user_bid_details_widget.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/get_bid_on_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/analytics_events/record_create_advert_action.dart
  libs/redux_comp/lib/actions/analytics_events/record_place_bid_action.dart
  libs/redux_comp/lib/actions/bids/delete_bid_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/process_payment_action.dart
  libs/redux_comp/lib/actions/remove_files_from_bucket_action.dart
  libs/redux_comp/lib/actions/user/open_in_maps_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/pubspec.yaml
Labels: Status : Ready, Priority:Medium, Scope : Back End

#477 💄 Final admin system fixes
  libs/admin/lib/pages/app_management/report_manage_page.dart
  libs/admin/lib/widgets/admin_user_widget.dart
Labels: Priority:Medium, Scope : Front End

#479 (Refactor): UI Fixes
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/widgets/accept_bid_popup.dart
  libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
  libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart
Labels: Scope : Front End

#478 Amplify
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createChatResolver/src/index.js
  libs/amplify/amplify/backend/function/sendMessageResolver/sendMessageResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/sendMessageResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/widgets/filter_popup.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/analytics_events/record_place_bid_action.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/actions/chat/send_message_action.dart
  libs/redux_comp/lib/actions/get_from_bucket_action.dart
  libs/redux_comp/lib/models/chat/chat_model.dart
  libs/redux_comp/lib/models/chat/message_model.dart
  libs/redux_comp/lib/models/filter_bids_model.dart
  libs/redux_comp/pubspec.yaml
  libs/redux_comp/test/filter_bids_action_test.dart
  libs/tradesman/lib/pages/advert_details.dart
Labels: Status : Ready, Priority:Medium, Scope : Back End

#485 Auth
  apps/app/lib/main.dart
  libs/admin/lib/admin.dart
  libs/admin/lib/pages/admin_manage_page.dart
  libs/admin/lib/pages/app_management/advert_reports/review_advert_reports_page.dart
  libs/admin/lib/pages/app_management/advert_reports/view_advert_reports_page.dart
  libs/admin/lib/pages/system_metrics/api_metrics_page.dart
  libs/admin/lib/pages/system_metrics/database_metrics_page.dart
  libs/admin/lib/pages/system_metrics/resolver_metrics_page.dart
  libs/admin/lib/pages/system_metrics_page.dart
  libs/admin/lib/pages/user_metrics/custom_metrics_page.dart
  libs/admin/lib/pages/user_metrics/sentiment_analysis_page.dart
  libs/admin/lib/pages/user_metrics_page.dart
  libs/admin/lib/widgets/admin_navbar_widget.dart
  libs/admin/lib/widgets/doughnut_chart_widget.dart
  libs/admin/lib/widgets/line_chart_widget.dart
  libs/admin/lib/widgets/quickview_chat_widget.dart
  libs/admin/lib/widgets/quickview_reported_advert_widget.dart
  libs/admin/lib/widgets/quickview_user_widget.dart
  libs/admin/lib/widgets/text_row_widget.dart
  libs/redux_comp/lib/actions/admin/app_management/get_reported_adverts_action.dart
  libs/redux_comp/lib/actions/admin/helper_functions/build_data.dart
  libs/redux_comp/lib/actions/admin/helper_functions/build_lambda_metric_query.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_api_metrics_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_db_metrics_action_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_lambda_metrics_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_errors_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_invocations_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_session_metrics_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/admin/admin_model.dart
  libs/redux_comp/lib/models/admin/app_management/admin_app_manage_model.dart
  libs/redux_comp/lib/models/admin/app_management/reported_advert_model.dart
  libs/redux_comp/lib/models/admin/user_metrics/user_metrics_model.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#486 Amplify
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner/Info.plist
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/acceptBidResolver/src/index.js
  libs/amplify/amplify/backend/function/processKinesisStreamResolver/src/index.js
  libs/amplify/amplify/backend/storage/User/parameters.json
  libs/amplify/amplify/team-provider-info.json
  libs/chat/lib/pages/chat_selection_page.dart
  libs/chat/lib/widgets/chat_appbar_widget.dart
  libs/chat/lib/widgets/quick_view_chat_widget.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/general/lib/widgets/profile_image.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/actions/user/get_profile_photo_action.dart
  libs/redux_comp/lib/actions/user/open_in_maps_action.dart
  libs/redux_comp/lib/models/chat/chat_model.dart
  libs/redux_comp/pubspec.yaml
  libs/redux_comp/test/advert_model_test.dart
  libs/tradesman/lib/pages/advert_details.dart
Labels: Status : Ready, Priority:Medium, Scope : Back End

#487 Amplify
  apps/app/lib/main.dart
  libs/admin/lib/pages/user_metrics/chat_sentiments_page.dart
  libs/admin/lib/pages/user_metrics/sentiment_analysis_page.dart
  libs/admin/lib/pages/user_metrics_page.dart
  libs/admin/lib/widgets/message_tile_widget.dart
  libs/admin/lib/widgets/quickview_chat_widget.dart
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/createChatResolver/src/index.js
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/amplify.state
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/getChatsSentimentResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/parameters.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/src/event.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/src/index.js
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/src/package.json
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getDashboardMetricsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getDashboardMetricsResolver/src/index.js
  libs/amplify/amplify/backend/function/getDashboardMetricsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/amplify.state
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/getGlobalSentimentResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/parameters.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/src/event.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/src/index.js
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/src/package.json
  libs/amplify/amplify/backend/function/getGlobalSentimentResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getMetricsResolver/src/index.js
  libs/amplify/amplify/backend/function/listMetricsResolver/amplify.state
  libs/amplify/amplify/backend/function/listMetricsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/listMetricsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/listMetricsResolver/listMetricsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/listMetricsResolver/src/event.json
  libs/amplify/amplify/backend/function/listMetricsResolver/src/index.js
  libs/amplify/amplify/backend/function/listMetricsResolver/src/package.json
  libs/amplify/amplify/backend/function/listMetricsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/processKinesisStreamResolver/src/index.js
  libs/amplify/amplify/backend/function/sendMessageResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/redux_comp/lib/actions/chat/get_messages_action.dart
  libs/redux_comp/lib/actions/chat/send_message_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/login_action.dart
  libs/redux_comp/lib/actions/user/sentiment/get_chats_sentiment_action.dart
  libs/redux_comp/lib/actions/user/sentiment/get_global_sentiment_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/chat/chat_model.dart
  libs/redux_comp/lib/models/chat/message_model.dart
  libs/redux_comp/lib/models/sentiment_model.dart
Labels: Status : Ready, Priority:High, Scope : Back End

#488 💫More widget tests
  execute_script.js
  libs/admin/test/admin_manage_page_test.dart
  libs/admin/test/admin_profile_test.dart
  libs/admin/test/admin_test.dart
  libs/admin/test/search_users_page_test.dart
  libs/admin/test/system_metrics_page_test.dart
  libs/admin/test/user_metrics_page_test.dart
  libs/admin/test/view_advert_reports_page_test.dart
  libs/admin/test/view_review_reports_page_test.dart
  libs/authentication/test/signup_page_test.dart
  libs/consumer/test/advert_details_test.dart
  libs/consumer/test/bid_details_page_test.dart
  libs/consumer/test/consumer_profile_page_test.dart
  libs/redux_comp/coverage/lcov.info
  libs/redux_comp/test/filter_bids_action_test.dart
Labels: Priority:Medium, Type: Test

#490 Auth
  libs/admin/lib/pages/app_management/user_manage_page.dart
  libs/admin/lib/pages/user_metrics/custom_metrics_page.dart
  libs/admin/lib/pages/user_metrics_page.dart
  libs/admin/lib/widgets/doughnut_chart_widget.dart
  libs/admin/lib/widgets/grouped_doughnut_chart_widget.dart
  libs/admin/lib/widgets/message_tile_widget.dart
  libs/admin/lib/widgets/partial_user_widget.dart
  libs/admin/lib/widgets/quickview_user_widget.dart
  libs/amplify/amplify/backend/function/getChatsSentimentResolver/src/package.json
  libs/amplify/amplify/team-provider-info.json
  libs/general/lib/widgets/appbar.dart
  libs/redux_comp/lib/actions/admin/app_management/admin_get_user_action.dart
  libs/redux_comp/lib/actions/admin/helper_functions/build_dimensions_query.dart
  libs/redux_comp/lib/actions/admin/helper_functions/build_line_data.dart
  libs/redux_comp/lib/actions/admin/helper_functions/build_pie_data.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_api_metrics_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_db_metrics_action_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_errors_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_invocations_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_adverts_place_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_adverts_type_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_bid_amount_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_place_bid_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_session_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/list_metrics_action.dart
  libs/redux_comp/lib/models/admin/app_management/admin_app_manage_model.dart
  libs/redux_comp/lib/models/admin/app_management/models/cognito_user_model.dart
  libs/redux_comp/lib/models/admin/app_metrics/metrics_model.dart
  libs/redux_comp/lib/models/admin/user_metrics/chart_model.dart
  libs/redux_comp/lib/models/admin/user_metrics/dimensions_model.dart
  libs/redux_comp/lib/models/admin/user_metrics/pie_chart_model.dart
  libs/redux_comp/lib/models/admin/user_metrics/user_metrics_model.dart
Labels: Priority:Medium

#491 Tradesman
  apps/app/lib/main.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/tradesman/lib/methods/populate_bids.dart
  libs/tradesman/lib/pages/bid_details_page.dart
  libs/tradesman/lib/widgets/quick_view_bid_widget.dart
Labels: Priority:High, Scope : Front End

#492 Auth
  libs/admin/lib/pages/app_management/users/search_users_page.dart
  libs/admin/lib/pages/user_metrics/custom_metrics_page.dart
  libs/general/lib/widgets/list_refresh_widget.dart
Labels: Priority:Medium, Type: Bug

#493 💫More unit tests
  libs/authentication/test/authentication_test.dart
  libs/consumer/test/accept_bid_popup_test.dart
  libs/consumer/test/consumer_profile_page_test.dart
  libs/consumer/test/delete_advert_popup_test.dart
  libs/consumer/test/limited_consumer_profile_page_test.dart
  libs/general/test/general_test.dart
  libs/tradesman/test/card_widget_test.dart
  libs/tradesman/test/quick_view_bid_widget_test.dart
  libs/tradesman/test/tradesman_test.dart
Labels: Type: Test

#494 Amplify
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/acceptBidResolver/src/index.js
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/amplify.state
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/archiveExpiredTrigger-cloudformation-template.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/custom-policies.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/function-parameters.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/parameters.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/src/event.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/src/index.js
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/src/package.json
  libs/amplify/amplify/backend/function/archiveExpiredTrigger/src/yarn.lock
  libs/amplify/amplify/backend/function/createAdvertResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/chat/lib/pages/chat_selection_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/pages/archived_jobs_page.dart
  libs/general/lib/widgets/list_refresh_widget.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/view_bids_page.dart
Labels: Status : Ready, Priority:Medium, Scope : Front End

#498 Auth
  apps/app/lib/main.dart
  documentation/Testing_Policy.pdf
  documentation/Usability_Testing_Report.pdf
  libs/admin/lib/admin.dart
  libs/admin/lib/pages/admin_profile_page.dart
  libs/admin/lib/pages/system_metrics/auth_metrics_page.dart
  libs/admin/lib/pages/system_metrics_page.dart
  libs/admin/lib/widgets/box_widget.dart
  libs/amplify/amplify/backend/function/editUserDetailResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/pages/view_quote_page.dart
  libs/consumer/lib/widgets/quick_view_bid.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_auth_metrics_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_errors_action.dart
  libs/redux_comp/lib/actions/admin/system_metrics/get_resolver_invocations_action.dart
  libs/redux_comp/lib/actions/user/amplify_auth/check_signed_in_action.dart
  libs/redux_comp/lib/actions/user/cognito/assign_groups_action.dart
  libs/redux_comp/lib/actions/user/cognito/refresh_user_token_action.dart
  libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
  libs/redux_comp/lib/models/admin/app_metrics/app_metrics_model.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/quick_view_bid_widget.dart
Labels: Priority:Low

#499 Amplify
  libs/consumer/lib/widgets/filter_popup.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/redux_comp/lib/models/job_type.dart
Labels: Status : Ready, Priority:Medium, Scope : Back End

#501 Amplify
  libs/admin/lib/pages/app_management/users/search_users_page.dart
  libs/admin/lib/pages/user_metrics/chat_sentiments_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/widgets/accept_bid_popup.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_adverts_type_metrics_action.dart
  libs/redux_comp/lib/actions/admin/user_metrics/get_bid_amount_metrics_action.dart
  libs/redux_comp/lib/actions/adverts/filter_adverts_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/chat/get_messages_action.dart
  libs/redux_comp/lib/actions/user/sentiment/get_chats_sentiment_action.dart
  libs/redux_comp/lib/actions/user/sentiment/get_global_sentiment_action.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
Labels: Priority:Medium

#502 Amplify
  libs/admin/lib/pages/app_management/report_manage_page.dart
  libs/admin/lib/pages/app_management/review_reports/review_report_manage_page.dart
  libs/admin/lib/pages/app_management/user_manage_page.dart
  libs/admin/lib/widgets/report_user_descr_widget.dart
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/addReviewReportResolver/src/index.js
  libs/amplify/amplify/backend/function/adminSearchUserResolver/src/index.js
  libs/amplify/amplify/backend/function/getReportsResolver/src/index.js
  libs/amplify/amplify/backend/function/listUsersResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/test/signup_page_test.dart
  libs/consumer/coverage/lcov.info
  libs/general/coverage/lcov.info
  libs/general/lib/pages/report_page.dart
  libs/redux_comp/coverage/lcov.info
  libs/redux_comp/lib/actions/admin/app_management/add_review_report_action.dart
  libs/redux_comp/lib/actions/admin/app_management/admin_search_user_action.dart
  libs/redux_comp/lib/actions/admin/app_management/enable_user_action.dart
  libs/redux_comp/lib/actions/admin/app_management/get_review_reports_action.dart
  libs/redux_comp/lib/actions/admin/app_management/list_users_action.dart
  libs/redux_comp/lib/models/admin/app_management/models/cognito_user_model.dart
  libs/redux_comp/lib/models/admin/app_management/models/list_users_model.dart
  libs/redux_comp/lib/models/admin/app_management/report_model.dart
  libs/tradesman/coverage/lcov.info
  libs/tradesman/lib/widgets/reviews/review_widget.dart
Labels: Priority:Medium
