Repository COS301-SE-2022/ReverseHand, pull requests merged in 2022-07, with the labels that each got.

#231 Latest Consumer UI for Adverts, Editing Adverts, Viewing Bids and Profiles
  apps/app/lib/main.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/bid_card.dart
  libs/general/lib/widgets/bottom_overlay.dart
  libs/general/lib/widgets/button.dart
  libs/general/lib/widgets/divider.dart
  libs/general/lib/widgets/floating_button.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/shortlist_accept_button.dart
Labels: Priority:Medium, Scope : Front End

#232 Added editAdvert reducer
  libs/redux_comp/lib/actions/edit_advert_action.dart
  libs/redux_comp/lib/models/advert_model.dart
Labels: Priority:Medium, Type: Enhancement, Scope : Back End

#255 🐛 Fix build.gradle file for android
  apps/app/android/build.gradle
Labels: Status : Ready, Type: Fix

#259 Consumer
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createUserResolver/src/index.js
  libs/amplify/amplify/backend/function/editBidResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/redux_comp/lib/actions/adverts/close_advert_action.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/models/filter_bids_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#262 (♺Refactor)
  apps/app/ios/OneSignalNotificationServiceExtension/Info.plist
  apps/app/ios/OneSignalNotificationServiceExtension/NotificationService.swift
  apps/app/ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements
  apps/app/ios/Podfile
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner.xcodeproj/project.pbxproj
  apps/app/ios/Runner/Runner.entitlements
  apps/app/lib/main.dart
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/location_page.dart
  libs/authentication/lib/pages/location_search_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/pubspec.yaml
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/geolocation/lib/place_api_service.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/adverts/set_active_ad_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/accept_bid_action.dart
  libs/redux_comp/lib/actions/bids/edit_bid_action.dart
  libs/redux_comp/lib/actions/bids/place_bid_action.dart
  libs/redux_comp/lib/actions/bids/set_active_bid_action.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/bids/toggle_view_bids_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/geolocation/get_place_action.dart
  libs/redux_comp/lib/actions/user/add_user_to_group_action.dart
  libs/redux_comp/lib/actions/user/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/create_user_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/actions/user/register_user_action.dart
  libs/redux_comp/lib/actions/user/verify_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/geolocation/address_model.dart
  libs/redux_comp/lib/models/geolocation/coordinates_model.dart
  libs/redux_comp/lib/models/geolocation/location_model.dart
  libs/redux_comp/lib/models/geolocation/place_model.dart
  libs/redux_comp/lib/models/geolocation/search_model.dart
  libs/redux_comp/lib/models/user_models/partial_user_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/redux_comp/test/redux_test.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/edit_bid_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/place_bid_popup.dart
Labels: Priority:High

#272 Redux
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/widgets/button.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/adverts/set_active_ad_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/accept_bid_action.dart
  libs/redux_comp/lib/actions/bids/edit_bid_action.dart
  libs/redux_comp/lib/actions/bids/set_active_bid_action.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/bids/toggle_view_bids_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/geolocation/get_place_action.dart
  libs/redux_comp/lib/actions/geolocation/get_suggestions_action.dart
  libs/redux_comp/lib/actions/user/add_user_to_group_action.dart
  libs/redux_comp/lib/actions/user/create_user_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/actions/user/register_user_action.dart
  libs/redux_comp/lib/actions/user/verify_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_models/partial_user_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/redux_comp/test/redux_test.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#275 (♺Refactor): Fixed getUserAction error that stops you from logging in
  libs/redux_comp/lib/actions/user/check_user_exists_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
Labels: Priority:High, Scope : Back End

#276 Consumer
  apps/app/lib/main.dart
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/authentication/lib/pages/location_page.dart
  libs/authentication/lib/pages/login_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/dialog_helper.dart
  libs/consumer/lib/widgets/rating_popup.dart
  libs/consumer/lib/widgets/rating_stars.dart
  libs/consumer/lib/widgets/shortlist_bid_popup.dart
  libs/consumer/lib/widgets/view_quote_pop_up.dart
  libs/consumer/lib/widgets/white_pop_up.dart
  libs/general/lib/widgets/appbar.dart
  libs/general/lib/widgets/button.dart
  libs/general/lib/widgets/loader.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/textfield.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/bids/shortlist_bid_action.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/view_bids_page.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#288 Consumer
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/removeDomainResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/viewBidsResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/login_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/delete_advert_popup.dart
  libs/consumer/lib/widgets/filter_popup.dart
  libs/consumer/lib/widgets/shortlist_bid_popup.dart
  libs/general/lib/widgets/bid_card.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/lib/actions/adverts/filter_bids_action.dart
  libs/redux_comp/lib/actions/bids/view_bids_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/models/filter_bids_model.dart
  libs/tradesman/lib/widgets/button_bar_widget.dart
  libs/tradesman/lib/widgets/card_widget.dart
Labels: Priority:Medium, Scope : Front End, Scope : Back End

#289 Consumer
  libs/consumer/lib/pages/advert_details_page.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/quick_view_bid.dart
Labels: Priority:Medium, Scope : Front End

#291 Consumer
  libs/redux_comp/lib/actions/changed_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/models/geolocation/location_model.dart
Labels: Priority:High, Scope : Back End

#292 (🐛Tradesman): Fixed some bugs yo
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/createChatResolver/amplify.state
  libs/amplify/amplify/backend/function/createChatResolver/createChatResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/createChatResolver/custom-policies.json
  libs/amplify/amplify/backend/function/createChatResolver/function-parameters.json
  libs/amplify/amplify/backend/function/createChatResolver/parameters.json
  libs/amplify/amplify/backend/function/createChatResolver/src/event.json
  libs/amplify/amplify/backend/function/createChatResolver/src/index.js
  libs/amplify/amplify/backend/function/createChatResolver/src/package.json
  libs/amplify/amplify/backend/function/createChatResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/amplify.state
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/custom-policies.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/function-parameters.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/getConsumerMessagesResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/parameters.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/src/event.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/src/index.js
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/src/package.json
  libs/amplify/amplify/backend/function/getConsumerMessagesResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/sendMessageResolver/amplify.state
  libs/amplify/amplify/backend/function/sendMessageResolver/custom-policies.json
  libs/amplify/amplify/backend/function/sendMessageResolver/function-parameters.json
  libs/amplify/amplify/backend/function/sendMessageResolver/parameters.json
  libs/amplify/amplify/backend/function/sendMessageResolver/sendMessageResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/sendMessageResolver/src/event.json
  libs/amplify/amplify/backend/function/sendMessageResolver/src/index.js
  libs/amplify/amplify/backend/function/sendMessageResolver/src/package.json
  libs/amplify/amplify/backend/function/sendMessageResolver/src/yarn.lock
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/geolocation/lib/pages/location_search_page.dart
  libs/redux_comp/lib/actions/changed_action.dart
  libs/redux_comp/lib/actions/geolocation/get_place_action.dart
  libs/redux_comp/lib/actions/geolocation/set_place_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/location_confirm_page.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
Labels: Status : Ready, Type: Bug

#300 Consumer
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/deleteAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/editAdvertResolver/editAdvertResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/editAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/editUserDetailResolver/src/index.js
  libs/amplify/amplify/backend/function/sendMessageResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/login_page.dart
  libs/chat/.dart_tool/package_config.json
  libs/chat/.dart_tool/package_config_subset
  libs/chat/.dart_tool/version
  libs/chat/.idea/libraries/Dart_SDK.xml
  libs/chat/.idea/modules.xml
  libs/chat/.idea/workspace.xml
  libs/chat/.packages
  libs/chat/chat.iml
  libs/chat/pubspec.lock
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/general/lib/widgets/appbar.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/loader.dart
  libs/general/lib/widgets/loading_widget.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/general/lib/widgets/skeleton_loader.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/edit_advert_action.dart
  libs/redux_comp/lib/actions/adverts/view_adverts_action.dart
  libs/redux_comp/lib/actions/user/get_user_action.dart
  libs/redux_comp/lib/actions/user/logout_action.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/error_type_model.dart
Labels: Priority:Medium

#307 Consumer
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/createChatResolver/src/index.js
  libs/amplify/amplify/backend/function/deleteChatResolver/src/index.js
  libs/amplify/amplify/backend/function/removeDomainResolver/amplify.state
  libs/amplify/amplify/backend/function/removeDomainResolver/custom-policies.json
  libs/amplify/amplify/backend/function/removeDomainResolver/function-parameters.json
  libs/amplify/amplify/backend/function/removeDomainResolver/parameters.json
  libs/amplify/amplify/backend/function/removeDomainResolver/removeDomainResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/removeDomainResolver/src/event.json
  libs/amplify/amplify/backend/function/removeDomainResolver/src/index.js
  libs/amplify/amplify/backend/function/removeDomainResolver/src/package.json
  libs/amplify/amplify/backend/function/viewBidsResolver/amplify.state
  libs/amplify/amplify/backend/function/viewBidsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/viewBidsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/viewBidsResolver/parameters.json
  libs/amplify/amplify/backend/function/viewBidsResolver/src/event.json
  libs/amplify/amplify/backend/function/viewBidsResolver/src/index.js
  libs/amplify/amplify/backend/function/viewBidsResolver/src/package.json
  libs/amplify/amplify/backend/function/viewBidsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/viewBidsResolver/viewBidsResolver-cloudformation-template.json
  libs/amplify/amplify/team-provider-info.json
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/widgets/action_bar_widget.dart
  libs/chat/lib/widgets/chat_appbar.dart
  libs/chat/lib/widgets/message_tile.dart
  libs/chat/lib/widgets/quick_view_chat_widget.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/rating_popup.dart
  libs/consumer/lib/widgets/rating_stars.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/lib/actions/chat/create_chat_action.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/chat/get_chats_action.dart
  libs/redux_comp/lib/actions/chat/subscribe_messages_action.dart
  libs/redux_comp/lib/actions/user/login_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/chat/chat_model.dart
Labels: Priority:High, Scope : Front End, Scope : Back End

#308 (♻️Refactor)
  apps/app/lib/main.dart
  apps/app/pubspec.lock
  libs/authentication/lib/pages/signup_page.dart
  libs/chat/lib/pages/chat_selection_page.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/appbar.dart
  libs/geolocation/lib/pages/location_confirm_page.dart
  libs/notifications/lib/notifications.dart
  libs/notifications/pubspec.yaml
  libs/notifications/test/notifications_test.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/user/create_user_action.dart
  libs/redux_comp/lib/actions/user/edit_user_details_action.dart
  libs/redux_comp/lib/models/geolocation/location_model.dart
  libs/tradesman/lib/pages/activity_stream_page.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/domain_confirmation_page.dart
  libs/tradesman/lib/pages/edit_bid_page.dart
  libs/tradesman/lib/pages/edit_bids_page.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/multiselect_widget.dart
  libs/tradesman/lib/widgets/navbar.dart
  libs/tradesman/lib/widgets/notification_card_widget.dart
  libs/tradesman/lib/widgets/place_bid_popup.dart
  libs/tradesman/lib/widgets/quick_view_bid.dart
  libs/tradesman/pubspec.yaml
Labels: Scope : Front End, Scope : Back End

#309 💄 final overflow fixes
  libs/consumer/lib/pages/view_bids_page.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/tradesman/lib/pages/view_bids_page.dart
Labels: Priority:High, Scope : Front End

#310 (💄Refactor & Tradesman)
  apps/app/lib/main.dart
  libs/chat/lib/pages/chat_selection_page.dart
  libs/chat/pubspec.yaml
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/view_bids_page.dart
  libs/consumer/lib/widgets/radio_select_widget.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/navbar.dart
  libs/geolocation/lib/pages/custom_location_search_page.dart
  libs/redux_comp/lib/actions/adverts/create_advert_action.dart
  libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
  libs/redux_comp/lib/actions/bids/set_active_bid_action.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/bid_details_page.dart
  libs/tradesman/lib/pages/edit_bid_page.dart
  libs/tradesman/lib/pages/edit_profile_page.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/pages/tradesman_profile_page.dart
  libs/tradesman/lib/pages/view_bids_page.dart
  libs/tradesman/lib/widgets/navbar.dart
  libs/tradesman/lib/widgets/quick_view_bid.dart
Labels: Status : Ready, Scope : Front End

#311 Consumer
  libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
  libs/amplify/amplify/backend/function/deleteChatResolver/deleteChatResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/deleteChatResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/chat/lib/pages/chat_page.dart
  libs/chat/lib/widgets/action_bar_widget.dart
  libs/chat/lib/widgets/action_button.dart
  libs/chat/lib/widgets/action_button_widget.dart
  libs/chat/lib/widgets/chat_appbar_widget.dart
  libs/chat/lib/widgets/message_tile_widget.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/widgets/rating_popup.dart
  libs/redux_comp/lib/actions/chat/delete_chat_action.dart
  libs/redux_comp/lib/actions/chat/send_message_action.dart
Labels: Priority:High, Scope : Back End

#315 Tests
  apps/app/integration_test/consumer_accept_bid.dart
  apps/app/integration_test/consumer_create_advert.dart
  apps/app/integration_test/consumer_edit_advert.dart
  apps/app/integration_test/consumer_filter_bids.dart
  apps/app/integration_test/consumer_login_test.dart
  apps/app/integration_test/consumer_view_ads_test.dart
  apps/app/integration_test/login_test.dart
  apps/app/integration_test/tradesman_login_test.dart
  apps/app/integration_test/tradesman_view_jobs.dart
  apps/app/integration_test/tradesman_view_place_bids.dart
  libs/tradesman/test/tradesman_test.dart
Labels: Priority:Medium

#287 ✨ Testing emulator
  .github/workflows/android.yml
  apps/app/integration_test/consumer2_test.dart
  apps/app/integration_test/consumer_accept_bid.dart
  apps/app/integration_test/consumer_edit_advert.dart
  apps/app/integration_test/consumer_filter_bids.dart
  apps/app/integration_test/consumer_view_ads_test.dart
  apps/app/integration_test/signup_test.dart
  apps/app/integration_test/tradesman_login_test.dart
  apps/app/integration_test/tradesman_view_jobs.dart
  apps/app/integration_test/tradesman_view_place_bids.dart
  apps/app/project.json
  libs/authentication/test/authentication_test.dart
  libs/chat/pubspec.yaml
  libs/chat/test/chat_test.dart
Labels: Priority:Medium, Scope: CI/CD
