Repository COS301-SE-2022/ReverseHand, pull requests merged in 2022-05, with the labels that each got.

#18 ✨ Added some code quality badges
  README.md
Labels: Type: Enhancement, Scope : Front End

#20 CI to execute and analyze code
  .github/workflows/android.yml
  .github/workflows/index.yml
Labels: Status : Ready, Priority:High, Type: Enhancement, Scope: CI/CD

#21 Added CI Tests badge for Build quality badge
  .github/workflows/android.yml
  README.md
  apps/app/pubspec.lock
Labels: Status : Ready, Type: Documentation

#22 Added build app bundle
  .github/workflows/android.yml
  apps/app/android/build.gradle
Labels: Status : Ready, Priority:High, Type: Enhancement, Scope: CI/CD

#24 💚 Building app bundle only for apps/app
  .github/workflows/android.yml
Labels: Type: Fix, Priority:Low, Scope: CI/CD

#23 ✨ Added classes and functions required for redux
  apps/app/lib/main.dart
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/example/.gitignore
  libs/example/.metadata
  libs/example/CHANGELOG.md
  libs/example/LICENSE
  libs/example/README.md
  libs/example/analysis_options.yaml
  libs/example/lib/example.dart
  libs/example/project.json
  libs/example/pubspec.yaml
  libs/example/test/example_test.dart
  libs/redux/.gitignore
  libs/redux/.metadata
  libs/redux/CHANGELOG.md
  libs/redux/LICENSE
  libs/redux/README.md
  libs/redux/analysis_options.yaml
  libs/redux/lib/app_state.dart
  libs/redux/lib/reducers/reducer.dart
  libs/redux/lib/redux.dart
  libs/redux/project.json
  libs/redux/pubspec.yaml
  libs/redux/test/redux_test.dart
  workspace.json
Labels: Status : Ready, Priority:Medium, Type: Enhancement, Scope : Back End

#25 :truck: Redux
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/redux_comp/.gitignore
  libs/redux_comp/.metadata
  libs/redux_comp/CHANGELOG.md
  libs/redux_comp/LICENSE
  libs/redux_comp/README.md
  libs/redux_comp/analysis_options.yaml
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/reducers/reducer.dart
  libs/redux_comp/lib/redux_comp.dart
  libs/redux_comp/project.json
  libs/redux_comp/pubspec.yaml
  libs/redux_comp/test/redux_test.dart
  workspace.json
Labels: Status : Ready, Priority:High, Type: Change, Scope : Front End

#27 :construction: Further redux implementation
  apps/app/lib/main.dart
  apps/app/test/widget_test.dart
  libs/example/lib/example.dart
  libs/example/pubspec.yaml
  libs/redux_comp/lib/actions/actions.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/redux_comp.dart
Labels: Status: Not Ready, Priority:Medium, Type: Enhancement, Status : Needs Tests, Scope : Front End

#36 CI_CD branch
  .github/workflows/android.yml
  .github/workflows/full.yml
  .github/workflows/index.yml
  README.md
Labels: Status : Ready, Priority:Medium, Type: Enhancement, Scope: CI/CD

#40 🔀Merge Login branch into Develop branch
  apps/app/lib/main.dart
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  apps/app/test/widget_test.dart
  libs/general/.gitignore
  libs/general/.metadata
  libs/general/CHANGELOG.md
  libs/general/LICENSE
  libs/general/README.md
  libs/general/analysis_options.yaml
  libs/general/lib/general.dart
  libs/general/lib/login.dart
  libs/general/project.json
  libs/general/pubspec.yaml
  libs/general/test/general_test.dart
  workspace.json
Labels: Status : Ready, Priority:Medium, Scope : Front End

#42 Attempt to see if CodeCov works
  .github/workflows/android.yml
  apps/app/project.json
  libs/example/project.json
  libs/general/project.json
  libs/redux_comp/project.json
  merge-reports.js
Labels: Status : Ready, Priority:Medium, Type: Enhancement, Scope: CI/CD

#41 :white_check_mark: Added mock test to general to pass CI/CD check
  libs/example/lib/example.dart
  libs/general/test/general_test.dart
Labels: Status : Ready, Priority:High, Type: Test, Type: Change, Scope: CI/CD

#46 :clown_face: Redux
  libs/example/lib/example.dart
  libs/redux_comp/lib/actions/actions/example_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/reducers/reducer.dart
  libs/redux_comp/lib/reducers/reducers/example_reducer.dart
Labels: Status : Ready, Priority:Medium, Type: Enhancement, Status : Needs Tests, Scope : Front End

#49 ✅ Added mock test to pass CI/CD
  README.md
  libs/consumer/project.json
  libs/consumer/test/consumer_test.dart
Labels: Status : Ready, Priority:Low, Type: Change, Scope: CI/CD

#55 Removed Cache
  .github/workflows/android.yml
  .github/workflows/full.yml
  .github/workflows/index.yml
  libs/consumer/lib/job_listings.dart
  libs/consumer/test/consumer_test.dart
  libs/general/lib/login.dart
  libs/tradesman/lib/job_listings.dart
  libs/tradesman/pubspec.yaml
Labels: Type: Fix, Priority:Low

#58 🔀Merge Consumer branch into Develop branch
  libs/consumer/lib/job_details.dart
  libs/consumer/lib/job_listings.dart
  libs/consumer/test/consumer_test.dart
  libs/tradesman/.dart_tool/package_config.json
  libs/tradesman/.dart_tool/package_config_subset
  libs/tradesman/.dart_tool/version
  libs/tradesman/.packages
  libs/tradesman/pubspec.lock
  libs/tradesman/pubspec.yaml
Labels: Priority:High, Scope : Front End

#71 💄 Updated UI in Tradesman branch
  apps/app/lib/main.dart
  apps/app/test/widget_test.dart
  libs/general/lib/general.dart
  libs/general/lib/login.dart
  libs/tradesman/.dart_tool/package_config.json
  libs/tradesman/.dart_tool/package_config_subset
  libs/tradesman/.packages
  libs/tradesman/lib/job_details.dart
  libs/tradesman/lib/job_listings.dart
Labels: Status : Ready, Priority:Medium, Type: Change, Scope : Front End

#70 :memo: Readme
  .vscode/launch.json
  README.md
Labels: Type: Documentation, Priority:Medium, Type: Enhancement

#75 :pencil2: removed { } from readme
  README.md
  libs/amplify/.gitignore
  libs/consumer/.gitignore
  libs/example/.gitignore
  libs/general/.gitignore
  libs/redux_comp/.gitignore
  libs/tradesman/.gitignore
  libs/tradesman/test/tradesman_test.dart
Labels: Priority:Medium

#76 :memo: Added link to linkedin and github for michael
  README.md
Labels: Priority:Medium

#77 :recycle: App now conforms to async_redux
  libs/amplify/.vscode/settings.json
Labels: Priority:Medium

#73 2nd Attempt Widgets tests PR
  libs/consumer/.gitignore
  libs/consumer/coverage/lcov.info
  libs/consumer/lib/consumer.dart
  libs/consumer/lib/create_new_job.dart
  libs/consumer/lib/job_listings.dart
  libs/consumer/test/consumer_test.dart
  libs/general/lib/login.dart
  libs/redux_comp/.gitignore
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/reducers/reducer.dart
  libs/redux_comp/lib/reducers/reducers/example_reducer.dart
  libs/redux_comp/lib/reducers/reducers/login_reducer.dart
  libs/redux_comp/lib/redux_comp.dart
  libs/tradesman/.gitignore
Labels: Priority:Medium, Type: Test, Scope : Front End

#80 ✅ Added widget test for login page
  libs/general/test/general_test.dart
Labels: Status : Ready, Priority:Medium, Type: Test, Scope : Front End

#83 ✅ Update the codecov setup
  .github/workflows/android.yml
  execute_script.js
  merge-reports.js
Labels: Status : Ready, Priority:Medium, Type: Test, Scope: CI/CD

#81 ✅ Added TradesmanJobListings Widget Test
  libs/tradesman/project.json
  libs/tradesman/test/tradesman_test.dart
Labels: Status : Ready, Priority:Medium, Type: Test, Scope : Front End

#86 ✅ Removed appBundle build
  .github/workflows/android.yml
  .github/workflows/full.yml
Labels: Status : Ready, Type: Fix, Priority:Medium, Scope: CI/CD

#85 :white_check_mark: Consumer
  libs/amplify/amplify/backend/api/reversehand/cli-inputs.json
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/consumer/coverage/lcov.info
  libs/consumer/lib/consumer.dart
  libs/consumer/lib/create_new_job.dart
  libs/consumer/lib/job_listings.dart
  libs/consumer/lib/methods/populate_job_listings.dart
  libs/consumer/lib/pages/create_new_job.dart
  libs/consumer/lib/pages/job_details.dart
  libs/consumer/lib/pages/job_listings.dart
  libs/consumer/pubspec.yaml
  libs/consumer/test/consumer_test.dart
  libs/redux_comp/lib/actions/create_advert_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/reducers/reducer.dart
  libs/redux_comp/lib/reducers/reducers/login_reducer.dart
Labels: Priority:High

#84 :white_check_mark: Redux
  libs/redux_comp/coverage/lcov.info
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/test/redux_test.dart
Labels: Status : Ready, Priority:High, Type: Test

#102 ✨(Consumer): job_details.dart dynamically created from job_listing.dart Inkwell onclick
  libs/consumer/lib/methods/populate_job_details.dart
  libs/consumer/lib/methods/populate_job_listings.dart
  libs/consumer/lib/pages/job_details.dart
Labels: Status : Ready, Priority:Low, Type: Change, Scope : Front End, Scope : Back End

#103 :recycle: Redux
  libs/redux_comp/lib/reducers/reducer.dart
  libs/redux_comp/lib/reducers/reducers/login_reducer.dart
Labels: Status : Ready, Type: Fix, Priority:High, Scope : Front End

#104 Changed the Consumer tests to match new changes
  libs/consumer/test/consumer_test.dart
Labels: Status : Ready, Priority:High, Type: Test, Type: Enhancement, Scope : Front End

#106 Merging latest code from develop into Main
  README.md
  libs/consumer/test/consumer_test.dart
Labels: Priority:High

#116 ✨ CI_CD
  libs/redux_comp/create_action.py
  libs/redux_comp/project.json
Labels: Status : Ready, Priority:Low, Scope: CI/CD

#117 ✨ Redux
  apps/app/ios/Podfile.lock
  apps/app/pubspec.lock
  libs/amplify/amplify/backend/api/reversehand/cli-inputs.json
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/auth/reversehandff259d33/cli-inputs.json
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/amplify/lib/amplify.dart
  libs/amplify/pubspec.yaml
  libs/amplify/test/amplify_test.dart
  libs/redux_comp/lib/actions/register_user_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/user_model.dart
  libs/redux_comp/lib/models/user_models/consumer_model.dart
  libs/redux_comp/lib/models/user_models/tradesman_model.dart
  libs/redux_comp/pubspec.yaml
  libs/redux_comp/test/redux_test.dart
Labels: Status : Ready, Priority:High, Scope : Back End

#127 ✨ CI/CD
  libs/amplify/project.json
  libs/consumer/project.json
  libs/general/project.json
  libs/redux_comp/project.json
  libs/tradesman/project.json
Labels: Priority:Low

#132 🎨 Removed Dead Code
  .github/workflows/index.yml
Labels: Status : Ready, Priority:Low, Type: Enhancement, Scope: CI/CD

#130 ✅ Added Test for Consumer Details Class
  libs/consumer/test/consumer_test.dart
Labels: Status : Ready, Priority:Medium, Type: Test, Type: Enhancement, Scope : Front End

#133 ⚡️ Attempt to exclude amplify folder from analyser
  .github/workflows/android.yml
Labels: Priority:Medium, Type: Enhancement, Scope: CI/CD

#134 🐛 Corrected command to exclude amplify
  .github/workflows/android.yml
Labels: Priority:Medium, Scope: CI/CD

#135 :heavy_plus_sign: Upgraded flutter
  apps/app/ios/Podfile.lock
  apps/app/ios/Runner/Info.plist
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/amplify/pubspec.yaml
  libs/authentication/.flutter-plugins-dependencies
  libs/authentication/lib/pages/login.dart
  libs/authentication/lib/pages/sign_up.dart
  libs/authentication/lib/widgets/button.dart
  libs/authentication/pubspec.yaml
  libs/consumer/pubspec.yaml
  libs/consumer/test/consumer_test.dart
  libs/example/pubspec.yaml
  libs/general/pubspec.yaml
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/pubspec.yaml
  libs/tradesman/pubspec.yaml
Labels: Status : Ready, Type: Fix, Priority:High, Scope : Front End

#136 💄 Merge Login branch containing updated SignUpUI
  libs/authentication/.flutter-plugins
  libs/authentication/.flutter-plugins-dependencies
  libs/authentication/.gitignore
  libs/authentication/lib/authentication.dart
  libs/authentication/lib/methods/populate_login.dart
  libs/authentication/lib/methods/populate_sign_up.dart
  libs/authentication/lib/pages/sign_up.dart
  libs/authentication/lib/widgets/button.dart
  libs/authentication/lib/widgets/divider.dart
  libs/authentication/lib/widgets/link.dart
  libs/authentication/lib/widgets/textfield.dart
Labels: Status : Ready, Priority:Medium, Scope : Front End

#137 ✅ Added LoginPage widget test
  libs/amplify/.gitignore
  libs/amplify/project.json
  libs/authentication/.flutter-plugins
  libs/authentication/.flutter-plugins-dependencies
  libs/authentication/.gitignore
  libs/authentication/project.json
  libs/authentication/test/authentication_test.dart
Labels: Status : Ready, Priority:Medium, Type: Test, Type: Enhancement, Scope : Front End
