Repository COS301-SE-2022/ReverseHand, pull requests merged in 2022-06, with the labels that each got.

#158 🔀 💄 Merge Tradesman branch with popup implementation
  libs/authentication/lib/methods/populate_login.dart
  libs/authentication/lib/methods/populate_sign_up.dart
  libs/authentication/lib/pages/login.dart
  libs/authentication/lib/widgets/button.dart
  libs/authentication/lib/widgets/link.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/authentication/lib/widgets/textfield.dart
  libs/authentication/test/authentication_test.dart
  libs/consumer/lib/methods/populate_job_details.dart
  libs/consumer/test/consumer_test.dart
  libs/general/lib/widgets/dialog_helper.dart
  libs/general/lib/widgets/pop_up.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/tradesman/lib/methods/populate_job_details.dart
  libs/tradesman/lib/methods/populate_job_listings.dart
  libs/tradesman/lib/pages/job_details.dart
  libs/tradesman/lib/pages/job_listings.dart
  libs/tradesman/lib/tradesman.dart
  libs/tradesman/lib/widgets/place_bid_popup.dart
  libs/tradesman/lib/widgets/rating_popup.dart
  libs/tradesman/lib/widgets/rating_stars.dart
  libs/tradesman/pubspec.yaml
  libs/tradesman/test/tradesman_test.dart
Labels: Status : Ready, Type: Fix, Scope : Front End

#159 ✨ Redux
  libs/redux_comp/README.md
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/user_model.dart
Labels: Priority:Medium

#162 ✨(Login & SignUp): Very basic login & signup working
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/auth/reversehand8526215b/parameters.json
  libs/amplify/amplify/backend/auth/reversehand8ac8d062/cli-inputs.json
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/shortListBidResolver/amplify.state
  libs/amplify/amplify/backend/function/shortListBidResolver/custom-policies.json
  libs/amplify/amplify/backend/function/shortListBidResolver/function-parameters.json
  libs/amplify/amplify/backend/function/shortListBidResolver/parameters.json
  libs/amplify/amplify/backend/function/shortListBidResolver/shortListBidResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/shortListBidResolver/src/event.json
  libs/amplify/amplify/backend/function/shortListBidResolver/src/index.js
  libs/amplify/amplify/backend/function/shortListBidResolver/src/package.json
  libs/amplify/amplify/backend/function/shortListBidResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/viewBidsResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/methods/populate_login.dart
  libs/authentication/lib/methods/populate_sign_up.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/consumer/lib/methods/populate_bid_details.dart
  libs/consumer/test/consumer_test.dart
  libs/general/lib/widgets/button.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/register_user_action.dart
  libs/redux_comp/lib/actions/verify_user_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/error_type_model.dart
  libs/redux_comp/lib/models/user_model.dart
  libs/redux_comp/lib/models/user_models/consumer_model.dart
  libs/redux_comp/lib/models/user_models/partial_user_model.dart
  libs/redux_comp/lib/models/user_models/tradesman_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/tradesman/lib/widgets/place_bid_popup.dart
  libs/tradesman/lib/widgets/rating_popup.dart
Labels: Status : Ready, Priority:High, Status : Needs Tests, Scope : Back End

#168 ✨Consumer
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/function/viewAdvertsResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/pages/login.dart
  libs/consumer/lib/methods/populate_bid_details.dart
  libs/consumer/lib/methods/populate_job_details.dart
  libs/consumer/lib/methods/populate_job_listings.dart
  libs/consumer/lib/methods/populate_shortlisted_bid.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/view_adverts_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/advert_model.dart
  libs/redux_comp/lib/models/job_type.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
Labels: Status : Ready, Type: Documentation, Priority:High, Scope : Front End, Scope : Back End

#152 Splitting up of buildspec.yml and adding emulator to workflow
  .github/aws/buildspec.yml
  .github/aws/buildspec1.yml
  .github/workflows/android.yml
  .github/workflows/full.yml
  .github/workflows/index.yml
  execute_script.js
Labels: Status : Ready, Priority:Low, Type: Enhancement, Scope: CI/CD

#179 ✨Tradesman
  apps/app/pubspec.yaml
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/assets/images/logo.png
  libs/authentication/lib/methods/populate_login.dart
  libs/authentication/lib/methods/populate_sign_up.dart
  libs/authentication/lib/widgets/textfield.dart
  libs/authentication/pubspec.yaml
  libs/general/lib/login.dart
  libs/general/lib/theme.dart
  libs/redux_comp/lib/actions/place_bid_action.dart
  libs/tradesman/lib/pages/job_details.dart
Labels: Priority:High, Scope : Front End

#185 ✨Consumer
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/amplify.state
  libs/amplify/amplify/backend/function/closeAdvertResolver/closeAdvertResolver-cloudformation-template.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/custom-policies.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/function-parameters.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/parameters.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/src/event.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/src/index.js
  libs/amplify/amplify/backend/function/closeAdvertResolver/src/package.json
  libs/amplify/amplify/backend/function/closeAdvertResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/placeBidResolver/src/index.js
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/authentication/lib/methods/populate_login.dart
  libs/consumer/lib/consumer.dart
  libs/consumer/lib/methods/populate_bid_details.dart
  libs/consumer/lib/methods/populate_create_new_job.dart
  libs/consumer/lib/methods/populate_job_details.dart
  libs/consumer/lib/methods/populate_job_listings.dart
  libs/consumer/lib/methods/populate_shortlisted_bid.dart
  libs/consumer/lib/pages/create_new_job.dart
  libs/consumer/lib/pages/job_details.dart
  libs/consumer/lib/pages/job_listings.dart
  libs/consumer/lib/pages/view_bid.dart
  libs/consumer/lib/pages/view_shortlisted_bid.dart
  libs/general/lib/widgets/card.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/shortlist_accept_button.dart
  libs/general/lib/widgets/tab.dart
  libs/general/lib/widgets/textfield.dart
  libs/redux_comp/lib/actions/accept_bid_action.dart
  libs/redux_comp/lib/actions/create_advert_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/set_active_ad_action.dart
  libs/redux_comp/lib/actions/set_active_bid_action.dart
  libs/redux_comp/lib/actions/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/toggle_view_bids_action.dart
  libs/redux_comp/lib/actions/view_adverts_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/tradesman/lib/methods/populate_job_details.dart
  libs/tradesman/lib/methods/populate_job_listings.dart
  libs/tradesman/lib/pages/job_details.dart
  libs/tradesman/lib/pages/job_listings.dart
  libs/tradesman/test/tradesman_test.dart
Labels: Status : Ready, Priority:High, Scope : Front End, Scope : Back End

#190 (General ♺): Created resolver & reducer and added comments to redux_comp
  libs/amplify/amplify/team-provider-info.json
  libs/redux_comp/lib/actions/accept_bid_action.dart
  libs/redux_comp/lib/actions/close_advert_action.dart
  libs/redux_comp/lib/actions/create_advert_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/logout_action.dart
  libs/redux_comp/lib/actions/place_bid_action.dart
  libs/redux_comp/lib/actions/register_user_action.dart
  libs/redux_comp/lib/actions/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/verify_user_action.dart
  libs/redux_comp/lib/actions/view_adverts_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
Labels: Status : Ready, Priority:Medium, Scope : Back End

#191 ♲Refactor
  apps/app/lib/main.dart
  libs/authentication/lib/authentication.dart
  libs/authentication/lib/methods/populate_sign_up.dart
  libs/authentication/lib/pages/login.dart
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/sign_up.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/lib/widgets/circle_blur_widget.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/authentication/lib/widgets/textfield.dart
  libs/consumer/lib/consumer.dart
  libs/consumer/lib/methods/populate_adverts.dart
  libs/consumer/lib/methods/populate_bid_details.dart
  libs/consumer/lib/methods/populate_bids.dart
  libs/consumer/lib/methods/populate_create_new_job.dart
  libs/consumer/lib/methods/populate_job_details.dart
  libs/consumer/lib/methods/populate_job_listings.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/create_new_job.dart
  libs/consumer/lib/pages/job_details.dart
  libs/consumer/lib/pages/job_listings.dart
  libs/consumer/lib/pages/view_bid.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/general/lib/widgets/shortlist_accept_button.dart
  libs/redux_comp/lib/actions/accept_bid_action.dart
  libs/redux_comp/lib/actions/create_advert_action.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/register_user_action.dart
  libs/redux_comp/lib/actions/set_active_bid_action.dart
  libs/redux_comp/lib/actions/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/toggle_view_bids_action.dart
  libs/redux_comp/lib/actions/verify_user_action.dart
  libs/redux_comp/lib/actions/view_adverts_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/tradesman/lib/methods/populate_job_listings.dart
Labels: Status : Ready, Type: Fix, Priority:High, Type: Change, Scope : Front End, Scope : Back End

#192 (✨General): I need my silly view_jobs action
  libs/amplify/amplify/backend/api/reversehand/schema.graphql
  libs/amplify/amplify/backend/backend-config.json
  libs/amplify/amplify/backend/function/viewJobsResolver/amplify.state
  libs/amplify/amplify/backend/function/viewJobsResolver/custom-policies.json
  libs/amplify/amplify/backend/function/viewJobsResolver/function-parameters.json
  libs/amplify/amplify/backend/function/viewJobsResolver/parameters.json
  libs/amplify/amplify/backend/function/viewJobsResolver/src/event.json
  libs/amplify/amplify/backend/function/viewJobsResolver/src/index.js
  libs/amplify/amplify/backend/function/viewJobsResolver/src/package.json
  libs/amplify/amplify/backend/function/viewJobsResolver/src/yarn.lock
  libs/amplify/amplify/backend/function/viewJobsResolver/viewJobsResolver-cloudformation-template.json
  libs/amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts
  libs/amplify/amplify/team-provider-info.json
  libs/redux_comp/lib/actions/view_jobs_action.dart
Labels: Status : Ready, Priority:Low, Scope : Back End

#193 (✨Refactor): WE DID IT 🎉🤩
  apps/app/lib/main.dart
  libs/amplify/amplify/team-provider-info.json
  libs/consumer/lib/pages/bid_details_page.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/logout_action.dart
  libs/redux_comp/lib/actions/place_bid_action.dart
  libs/redux_comp/lib/actions/shortlist_bid_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/redux_comp/lib/actions/view_jobs_action.dart
  libs/tradesman/lib/methods/populate_adverts.dart
  libs/tradesman/lib/methods/populate_bids.dart
  libs/tradesman/lib/methods/populate_job_details.dart
  libs/tradesman/lib/methods/populate_job_listings.dart
  libs/tradesman/lib/pages/advert_details.dart
  libs/tradesman/lib/pages/job_details.dart
  libs/tradesman/lib/pages/job_listings.dart
  libs/tradesman/lib/pages/tradesman_listings.dart
  libs/tradesman/lib/tradesman.dart
  libs/tradesman/lib/widgets/place_bid_popup.dart
Labels: Status : Ready, Priority:Medium, Scope : Front End, Scope : Back End

#194 :recycle: Refactor
  libs/consumer/lib/methods/populate_bids.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/tradesman/lib/methods/populate_bids.dart
Labels: Priority:High, Type: Change, Scope : Front End

#199 Introducing tests on refactored code
  apps/app/.gitignore
  apps/app/coverage/lcov.info
  apps/app/integration_test/app_test.dart
  apps/app/integration_test/login_test.dart
  apps/app/integration_test/signup_test.dart
  apps/app/pubspec.lock
  apps/app/pubspec.yaml
  libs/amplify/test/amplify_test.dart
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/test/authentication_test.dart
  libs/consumer/test/consumer_test.dart
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/test/redux_test.dart
  libs/tradesman/test/tradesman_test.dart
Labels: Status : Ready, Priority:High, Type: Test, Type: Enhancement, Scope : Front End, Scope : Back End

#202 🐛 Fixing indentation error
  .github/aws/buildspec.yml
  execute_script.js
Labels: Priority:High, Type: Bug, Scope: CI/CD

#201 Refactor
  libs/authentication/lib/pages/signup_page.dart
  libs/consumer/lib/methods/populate_bids.dart
  libs/general/lib/widgets/quick_view_bid.dart
  libs/redux_comp/lib/actions/login_action.dart
  libs/redux_comp/lib/actions/place_bid_action.dart
  libs/redux_comp/lib/actions/register_user_action.dart
  libs/redux_comp/lib/actions/view_bids_action.dart
  libs/redux_comp/lib/app_state.dart
  libs/redux_comp/lib/models/bid_model.dart
  libs/redux_comp/lib/models/user_models/user_model.dart
  libs/redux_comp/test/redux_test.dart
  libs/tradesman/lib/methods/populate_bids.dart
Labels: Status : Ready, Type: Documentation, Priority:High, Scope : Front End

#203 (♺Refactor): Shortlisted_bids fixed bug
  apps/app/ios/Podfile.lock
  libs/redux_comp/lib/actions/init_amplify_action.dart
  libs/redux_comp/lib/actions/shortlist_bid_action.dart
Labels: Status : Ready, Priority:Low, Scope : Back End

#204 Added more integration tests
  apps/app/integration_test/app_test.dart
  apps/app/integration_test/consumer2_test.dart
  apps/app/integration_test/tradesman_login_test.dart
Labels: Status : Ready, Priority:High, Type: Test, Type: Enhancement

#206 💚 Attempt to fix bad executable error in pipeline
  .github/workflows/android.yml
Labels: Type: Fix, Priority:Medium, Scope: CI/CD

#214 💄Authentication related UI Updates
  apps/app/lib/main.dart
  libs/authentication/assets/images/apple.png
  libs/authentication/assets/images/facebook.png
  libs/authentication/assets/images/google.png
  libs/authentication/lib/pages/login_page.dart
  libs/authentication/lib/pages/signup_page.dart
  libs/authentication/lib/widgets/circle_blur_widget.dart
  libs/authentication/lib/widgets/otp_pop_up.dart
  libs/general/lib/widgets/blue_button_widget.dart
  libs/general/lib/widgets/pop_up.dart
Labels: Status : Ready, Scope : Front End

#218 UI for appBar, navBar and profiles
  apps/app/lib/main.dart
  libs/consumer/lib/pages/advert_details_page.dart
  libs/consumer/lib/pages/bid_details_page.dart
  libs/consumer/lib/pages/consumer_listings_page.dart
  libs/consumer/lib/pages/consumer_profile_page.dart
  libs/consumer/lib/pages/create_new_advert_page.dart
  libs/consumer/lib/pages/edit_profile_page.dart
  libs/consumer/test/consumer_test.dart
  libs/general/lib/theme.dart
  libs/general/lib/widgets/appbar.dart
  libs/general/lib/widgets/bid_card.dart
  libs/general/lib/widgets/bottom_overlay.dart
  libs/general/lib/widgets/button.dart
  libs/general/lib/widgets/job_card.dart
  libs/general/lib/widgets/navbar.dart
  libs/general/lib/widgets/quick_view_job_card.dart
  libs/general/lib/widgets/textfield.dart
  libs/general/pubspec.yaml
  libs/redux_comp/lib/actions/init_amplify_action.dart
Labels: Priority:Medium, Scope : Front End
